title: MFAA General Conference 2016
description: Immigration: From Integration to Citizenship
author: MFAA
logo: ./static/img/avatar.png
about: Moroccan Fulbright Alumni Association

baseurl: "https://yassines.github.io/MFAA_GeneralConf_2016.github.io/"
url: "https://yassines.github.io/MFAA_GeneralConf_2016.github.io/"

google_analytics: #UA-72862926-1 #TODO

share:
  twitter_username: \# #TODO
  fb_appid: 000000000000 #TODO


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
